### ISSUE TITLE
Listview styles

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/Atlas-theme-default#38] opened 2019-08-07 05:31 UTC
With Atlas 2.1.0, the default listview style has become bordered: lines between the listview items and a rounded border around the entire listview, listview-lined seems to have no effect. Is this by design?

**Comment by wegiswes** [comment] 2019-08-07 09:19
Hi!

This is not by design. This is caused by the integration of mxui.scss in Atlas. The specificity is different compared to core styling which causes unexpected issues. mxui will be integrated in core over time. For now, the borders and border radius are removed and the fix will be in the next Atlas release.

The class `listview-lined` doesn't exist. It wasn't there in Atlas 1.x either. Perhaps you are confused with `listview-striped`? [Listview Helpers](https://github.com/mendix/Atlas-UI-Framework/blob/release/styles/web/sass/core/helpers/_listview.scss)

**Comment by mgroeneweg** [comment] 2019-08-07 09:35
Yes, it is listview-striped, it is called lined on the Atlas sample site.

**Comment by wegiswes** [comment] 2019-08-07 11:16
Ah, I will make sure this is changed on the website. Thanks!

**Closed as completed** 2020-10-02 09:43 UTC
